# Generated by Django 6.0.2 on 2026-03-22 08:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import registros.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.CharField(db_index=True, max_length=5)),
                ('estado', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('colonias', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Corralón')),
                ('calle', models.CharField(max_length=255)),
                ('colonia', models.CharField(max_length=150)),
                ('cp', models.CharField(max_length=5, verbose_name='Código Postal')),
                ('municipio', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=100)),
                ('ubicacion_completa', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('estatus_deposito', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('PAUSADO', 'Pausado')], default='ACTIVO', max_length=30)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'ordering': ['-creado_el'],
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apaterno', models.CharField(max_length=100)),
                ('amaterno', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('identificacion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección completa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('SUPER', 'Super Usuario Secretaría'), ('ADMIN', 'Administrador SMyT'), ('OPERADOR', 'Usuario Concesionario')], default='SUPER', max_length=10)),
                ('nombre_user', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('aPaterno_user', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('aMaterno_user', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono_user', models.CharField(blank=True, max_length=20)),
                ('estatus_user', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.deposito')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=100)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('PARTICULAR', 'Particular'), ('PUBLICO', 'Público'), ('ESPECIALIZADO', 'Especializado')], max_length=20)),
                ('tipo_registro', models.CharField(choices=[('NUEVO', 'Ingreso Ordinario'), ('INVENTARIO', 'Carga de Inventario')], default='NUEVO', max_length=20)),
                ('folio', models.CharField(blank=True, max_length=50, unique=True)),
                ('autoridad_ingreso', models.CharField(max_length=200)),
                ('presencia_factura', models.BooleanField(default=False)),
                ('factura_original', models.FileField(blank=True, null=True, upload_to=registros.models.ruta_documentos)),
                ('lugar_siniestro', models.TextField()),
                ('motivo_ingreso', models.TextField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_aqui', to='registros.deposito')),
            ],
        ),
        migrations.CreateModel(
            name='FotoEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Frontal, Lateral Izquierdo, Llanta extra...', max_length=150)),
                ('foto', models.ImageField(upload_to=registros.models.ruta_fotos_evidencia)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('es_solicitud', models.BooleanField(default=False)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='ACEPTADA', max_length=20)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=255, null=True)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_evidencia', to='registros.ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='EstatusLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion_juridica', models.CharField(max_length=200)),
                ('num_oficio', models.CharField(max_length=100)),
                ('documento_oficio', models.FileField(upload_to=registros.models.ruta_documentos)),
                ('fecha_oficio', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatus_legales', to='registros.ingreso')),
            ],
            options={
                'verbose_name_plural': 'Estatus Legales',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DetallesAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus_carroceria', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('DAÑADO', 'Dañado')], max_length=20)),
                ('estatus_cristales', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('DAÑADO', 'Dañado')], max_length=20)),
                ('estatus_espejos', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('DAÑADO', 'Dañado')], max_length=20)),
                ('cant_llantas_delanteras', models.PositiveIntegerField(default=2)),
                ('cant_llantas_traseras', models.PositiveIntegerField(default=2)),
                ('estado_asientos', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('DAÑADO', 'Dañado')], max_length=20)),
                ('vehiculo_sin_danos', models.BooleanField(default=False, verbose_name='¿El vehículo no presenta daños?')),
                ('estado_motor', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('DAÑADO', 'Dañado')], max_length=20)),
                ('cilindros', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_asientos', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_combustible', models.CharField(blank=True, max_length=50, null=True)),
                ('presencia_bateria', models.BooleanField(default=True)),
                ('tipo_transmision', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICA', 'Automática'), ('SEMIAUTOMATICA', 'Semiautomática')], max_length=20)),
                ('estatus_odometro', models.CharField(choices=[('FUNCIONAL', 'Funcional'), ('ROTO', 'Roto'), ('SIN_PANTALLA', 'Sin pantalla'), ('ILEGIBLE', 'Ilegible')], default='FUNCIONAL', max_length=20)),
                ('kilometraje_odometro', models.PositiveIntegerField(blank=True, null=True)),
                ('estatus_aceite_motor', models.CharField(choices=[('LLENO', 'Lleno'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo'), ('VACIO', 'Vacío')], max_length=20)),
                ('estatus_anticongelante', models.CharField(choices=[('LLENO', 'Lleno'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo'), ('VACIO', 'Vacío')], max_length=20)),
                ('estatus_combustible', models.CharField(choices=[('LLENO', 'Lleno'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo'), ('VACIO', 'Vacío')], max_length=20)),
                ('estatus_bolsas_aire', models.CharField(default='INTACTAS', max_length=20)),
                ('observaciones_detalladas', models.TextField(blank=True, null=True)),
                ('ingreso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial_detalles', to='registros.ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('identificacion_ok', models.BooleanField(default=True, verbose_name='Datos ID (Placas/VIN) correctos')),
                ('inventario_ok', models.BooleanField(default=True, verbose_name='Inventario físico verificado')),
                ('estado_fisico_ok', models.BooleanField(default=True, verbose_name='Daños físicos validados con fotos')),
                ('documentacion_ok', models.BooleanField(default=True, verbose_name='Documentación legible')),
                ('resultado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado (Requiere Corrección)'), ('OBSERVADO', 'Aprobado con Observaciones')], default='APROBADO', max_length=20)),
                ('observaciones_admin', models.TextField(blank=True, verbose_name='Comentarios del Administrador')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspeccion', to='registros.ingreso')),
            ],
            options={
                'verbose_name': 'Inspección Administrativa',
                'verbose_name_plural': 'Inspecciones Administrativas',
            },
        ),
        migrations.CreateModel(
            name='Liberacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('quien_recibe', models.CharField(max_length=200, verbose_name='Nombre de quien retira')),
                ('identificacion_recibe', models.CharField(max_length=100, verbose_name='Identificación (INE/Licencia)')),
                ('autoridad_autoriza', models.CharField(max_length=150, verbose_name='Autoridad que liberó')),
                ('numero_oficio_liberacion', models.CharField(max_length=100, verbose_name='No. de Oficio')),
                ('observaciones_salida', models.TextField(blank=True, null=True)),
                ('ingreso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liberacion', to='registros.ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado_objeto', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], default='BUENO', max_length=20)),
                ('foto_objeto', models.ImageField(blank=True, null=True, upload_to=registros.models.ruta_fotos_objetos)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos_encontrados', to='registros.ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte_vehiculo', models.CharField(help_text='Ej: Defensa delantera, Parabrisas', max_length=100, verbose_name='Parte afectada')),
                ('descripcion', models.TextField(verbose_name='Descripción del daño')),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to=registros.models.ruta_fotos_danos)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danos', to='registros.ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudEdicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla_destino', models.CharField(blank=True, max_length=50, null=True)),
                ('justificacion', models.TextField()),
                ('registro_id', models.IntegerField()),
                ('campo_afectado', models.CharField(max_length=100)),
                ('valor_viejo', models.TextField()),
                ('valor_nuevo', models.TextField()),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15)),
                ('evidencia_solicitud', models.ImageField(blank=True, null=True, upload_to=registros.models.ruta_solicitudes_temporales)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_acepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('submarca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('color_original', models.CharField(max_length=50)),
                ('color_actual', models.CharField(max_length=50)),
                ('num_serie', models.CharField(max_length=50, unique=True)),
                ('placas', models.CharField(max_length=20)),
                ('numero_motor', models.CharField(max_length=50)),
                ('repuve', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('estatus_actual', models.CharField(choices=[('DENTRO', 'En Depósito'), ('LIBERADO', 'Fuera / Entregado'), ('TRANSFERIDO', 'Transferido')], default='LIBERADO', max_length=20)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='registros.propietario')),
            ],
        ),
        migrations.AddField(
            model_name='ingreso',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.vehiculo'),
        ),
        migrations.CreateModel(
            name='HashVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_hash', models.CharField(max_length=255)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.vehiculo')),
            ],
        ),
    ]
