# Generated by Django 6.0.2 on 2026-02-25 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apaterno', models.CharField(max_length=100)),
                ('amaterno', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('identificacion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=100)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudEdicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificacion', models.TextField()),
                ('registro_id', models.IntegerField()),
                ('campo_afectado', models.CharField(max_length=100)),
                ('valor_viejo', models.TextField()),
                ('valor_nuevo', models.TextField()),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15)),
                ('usuario_acepto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('color_original', models.CharField(max_length=50)),
                ('color_actual', models.CharField(max_length=50)),
                ('num_serie', models.CharField(max_length=50, unique=True)),
                ('placas', models.CharField(max_length=20)),
                ('numero_motor', models.CharField(max_length=50)),
                ('tipo_servicio', models.CharField(choices=[('PARTICULAR', 'Particular'), ('PUBLICO', 'Público'), ('ESPECIALIZADO', 'Especializado')], max_length=20)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: Gato hidráulico, Laptop, Herramientas', max_length=200)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado_objeto', models.CharField(choices=[('BUENO', 'Buen Estado'), ('REGULAR', 'Desgastado/Usado'), ('MALO', 'Dañado/Roto'), ('S/N', 'Sin especificar')], default='S/N', max_length=20)),
                ('foto_evidencia', models.ImageField(blank=True, help_text='Foto del objeto o del conjunto de objetos', null=True, upload_to='objetos/evidencia/')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos_encontrados', to='registros.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('autoridad_ingreso', models.CharField(max_length=200)),
                ('presencia_factura', models.BooleanField(default=False)),
                ('factura_original', models.CharField(blank=True, max_length=100, null=True)),
                ('lugar_siniestro', models.TextField()),
                ('motivo_ingreso', models.TextField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='HashVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_hash', models.CharField(max_length=255)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='EstatusLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion_juridica', models.CharField(max_length=200)),
                ('num_oficio', models.CharField(max_length=100)),
                ('documento_oficio', models.CharField(max_length=100)),
                ('fecha_oficio', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus_carroceria', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('DAÑADO', 'Dañado')], max_length=20)),
                ('estatus_cristales', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('DAÑADO', 'Dañado')], max_length=20)),
                ('estatus_espejos', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('DAÑADO', 'Dañado')], max_length=20)),
                ('cant_llantas_delanteras', models.PositiveIntegerField(default=2)),
                ('cant_llantas_traseras', models.PositiveIntegerField(default=2)),
                ('estado_motor', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('DAÑADO', 'Dañado')], max_length=20)),
                ('presencia_bateria', models.BooleanField(default=True)),
                ('tipo_transmision', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICA', 'Automática'), ('SEMIAUTOMATICA', 'Semi_Automática')], max_length=20)),
                ('estado_asientos', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('DAÑADO', 'Dañado')], max_length=20)),
                ('estatus_aceite_motor', models.CharField(choices=[('LLENO', 'Lleno'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo'), ('VACIO', 'Vacío')], max_length=20)),
                ('estatus_anticongelante', models.CharField(choices=[('LLENO', 'Lleno'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo'), ('VACIO', 'Vacío')], max_length=20)),
                ('estatus_combustible', models.CharField(choices=[('LLENO', 'Lleno'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo'), ('VACIO', 'Vacío')], max_length=20)),
                ('estatus_bolsas_aire', models.CharField(default='INTACTAS', max_length=20)),
                ('evidencia_foto_frontal', models.ImageField(blank=True, null=True, upload_to='detalles/frontal/')),
                ('evidencia_foto_lateral', models.ImageField(blank=True, null=True, upload_to='detalles/lateral/')),
                ('evidencia_foto_interior', models.ImageField(blank=True, null=True, upload_to='detalles/interior/')),
                ('observaciones_detalladas', models.TextField(blank=True, null=True)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_fisicos', to='registros.vehiculo')),
            ],
        ),
    ]
