# Generated by Django 6.0.2 on 2026-03-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigopostal',
            name='estado',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='codigopostal',
            name='municipio',
            field=models.CharField(max_length=200),
        ),
    ]
