# Generated by Django 6.0.2 on 2026-03-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_alter_codigopostal_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigopostal',
            name='estado',
            field=models.CharField(max_length=210),
        ),
        migrations.AlterField(
            model_name='codigopostal',
            name='municipio',
            field=models.CharField(max_length=210),
        ),
    ]
