# Generated by Django 6.0.2 on 2026-02-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_propietario_bitacora_solicitudedicion_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatuslegal',
            name='documento_oficio',
            field=models.FileField(upload_to='oficios/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='factura_original',
            field=models.FileField(blank=True, null=True, upload_to='facturas/%Y/%m/%d/'),
        ),
    ]
