# Generated by Django 6.0.2 on 2026-02-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_estatuslegal_documento_oficio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='estatus_actual',
            field=models.CharField(choices=[('DENTRO', 'En Depósito'), ('LIBERADO', 'Fuera / Entregado'), ('TRANSFERIDO', 'Transferido a otra instancia')], default='DENTRO', max_length=20),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='tipo_registro',
            field=models.CharField(choices=[('NUEVO', 'Ingreso Ordinario'), ('INVENTARIO', 'Carga de Inventario (Auto ya presente)')], default='NUEVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha_ingreso',
            field=models.DateTimeField(),
        ),
    ]
