# Generated by Django 6.0.2 on 2026-03-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_codigopostal_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoevidencia',
            name='nombre',
            field=models.CharField(help_text='Ej: Frontal, Lateral Izquierdo, Llanta extra...', max_length=250),
        ),
    ]
