# Generated by Django 6.0.2 on 2026-02-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_ingreso_estatus_actual_ingreso_tipo_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesauto',
            name='estatus_odometro',
            field=models.CharField(choices=[('FUNCIONAL', 'Funcional / Legible'), ('ROTO', 'Roto / Dañado'), ('SIN_PANTALLA', 'Sin pantalla (Digital apagado)'), ('ILEGIBLE', 'Ilegible / Alterado')], default='FUNCIONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='detallesauto',
            name='kilometraje_odometro',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
