# Generated by Django 6.0.2 on 2026-03-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_alter_fotoevidencia_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudedicion',
            name='campo_afectado',
            field=models.CharField(max_length=300),
        ),
    ]
