# Generated by Django 6.0.2 on 2026-03-23 01:09

import registros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_alter_solicitudedicion_campo_afectado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoevidencia',
            name='foto',
            field=models.ImageField(max_length=500, upload_to=registros.models.ruta_fotos_evidencia),
        ),
        migrations.AlterField(
            model_name='solicitudedicion',
            name='evidencia_solicitud',
            field=models.ImageField(blank=True, max_length=550, null=True, upload_to=registros.models.ruta_solicitudes_temporales),
        ),
    ]
