# Generated by Django 6.0.2 on 2026-02-26 20:07

import django.db.models.deletion
import django.utils.timezone
import registros.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_detallesauto_estatus_odometro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estatuslegal',
            options={'ordering': ['-fecha_registro']},
        ),
        migrations.RemoveField(
            model_name='detallesauto',
            name='evidencia_foto_lateral',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='estatus_actual',
        ),
        migrations.RemoveField(
            model_name='objetopersonal',
            name='foto_evidencia',
        ),
        migrations.AddField(
            model_name='detallesauto',
            name='evidencia_foto_capo',
            field=models.ImageField(blank=True, null=True, upload_to=registros.models.path_evidencia_vehiculo),
        ),
        migrations.AddField(
            model_name='detallesauto',
            name='evidencia_foto_lateral_derecha',
            field=models.ImageField(blank=True, null=True, upload_to=registros.models.path_evidencia_vehiculo),
        ),
        migrations.AddField(
            model_name='detallesauto',
            name='evidencia_foto_lateral_izquierda',
            field=models.ImageField(blank=True, null=True, upload_to=registros.models.path_evidencia_vehiculo),
        ),
        migrations.AddField(
            model_name='estatuslegal',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objetopersonal',
            name='foto_objeto',
            field=models.ImageField(blank=True, null=True, upload_to=registros.models.path_objetos_vehiculo),
        ),
        migrations.AddField(
            model_name='solicitudedicion',
            name='fecha_aceptacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudedicion',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='estatus_actual',
            field=models.CharField(choices=[('DENTRO', 'En Depósito'), ('LIBERADO', 'Fuera / Entregado'), ('TRANSFERIDO', 'Transferido')], default='DENTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='detallesauto',
            name='estatus_odometro',
            field=models.CharField(choices=[('FUNCIONAL', 'Funcional'), ('ROTO', 'Roto'), ('SIN_PANTALLA', 'Sin pantalla'), ('ILEGIBLE', 'Ilegible')], default='FUNCIONAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='detallesauto',
            name='evidencia_foto_frontal',
            field=models.ImageField(blank=True, null=True, upload_to=registros.models.path_evidencia_vehiculo),
        ),
        migrations.AlterField(
            model_name='detallesauto',
            name='evidencia_foto_interior',
            field=models.ImageField(blank=True, null=True, upload_to=registros.models.path_evidencia_vehiculo),
        ),
        migrations.AlterField(
            model_name='detallesauto',
            name='tipo_transmision',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICA', 'Automática'), ('SEMIAUTOMATICA', 'Semiautomática')], max_length=20),
        ),
        migrations.AlterField(
            model_name='detallesauto',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_detalles', to='registros.vehiculo'),
        ),
        migrations.AlterField(
            model_name='estatuslegal',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_legal', to='registros.vehiculo'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='folio',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='tipo_registro',
            field=models.CharField(choices=[('NUEVO', 'Ingreso Ordinario'), ('INVENTARIO', 'Carga de Inventario')], default='NUEVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='objetopersonal',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='objetopersonal',
            name='estado_objeto',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], default='BUENO', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudedicion',
            name='usuario_acepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estatus_user',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=10),
        ),
        migrations.DeleteModel(
            name='Inspeccion',
        ),
    ]
