# Generated by Django 6.0.2 on 2026-03-25 03:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_alter_fotoevidencia_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatuslegal',
            name='documento_oficio',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='documento'),
        ),
    ]
